### ISSUE TITLE
[BUG] Malleable profile information not reconstructed completely

### ISSUE THREAD

**Issue by 0xShkk** [mgeeky/RedWarden#12]
When a malleable profile contains additional parameter URI schemes at the client block, this information will not be used at the URI filter allow list for letting malleable traffic pass through.

For example, if my malleable profile looks like this:

```
http-get "default" {

        set uri "/abc.php";

        client {

                metadata {
                        header "Cookie";
                }

                parameter "parametername" "value";

        }
```

A legit beacon request would be:

```
GET /abc.php?parametername=value
```

But RedWarden will drop this request as it expects `GET /abc.php` only.

As a workaround, one can supply the additional GET parameter values inside the malleable profile supplied to RedWarden like so:

```
http-get "default" {

        set uri "/abc.php?parametername=value";

        client {

                metadata {
                        header "Cookie";
                }
        }
```

**Comment by mgeeky** [comment]
Hi,

That's a superb catch! Thank you for reporting this bug, will address it as soon as I can.

Regards,
Mariusz.

**Comment by mgeeky** [comment]
Wooah, such a shame I forgot about this issue. Awesome job @eqn-group , thanks!
Closing it now. Feel free to reopen if problem remains.
