### ISSUE TITLE
Can not load profile configuration

### ISSUE THREAD

**Issue by avi8892** [mgeeky/RedWarden#4]
While trying to load any profile (I'm using the deafult profiles which can be found on Cobalt-strike's took kit), I'm getting the following errors:

![image](https://user-images.githubusercontent.com/31028818/127709247-68e0033d-37f4-4c6c-812e-af0afb43c33d.png)

**Comment by mgeeky** [comment]
This issue should be addressed in commit [67076d6](https://github.com/mgeeky/RedWarden/commit/67076d610f4f83148787b58cddc1f926171a8c22). Please let me know if the problem persists.

M.
