### ISSUE TITLE
dns beacon

### ISSUE THREAD

**Issue by fendi1989** [mgeeky/RedWarden#6]
seems like red warden completely ignored the dns config listener. it generates the default config of dns beacon with 0.0.0.0 as idle and all default params.
is there any fix for that ? Does redwarden handles dns ?
thx

**Comment by mgeeky** [comment]
Hi,

Thanks for your issue request. 
The RedWarden acts as a HTTP Proxy, therefore it does not support DNS.

Thanks,
M.

**Comment by fendi1989** [comment]
thx :) great project here , I like it and use it.

**Comment by mgeeky** [comment]
Glad to here that!

I'm closing the issue now. Let me know if anything else pops up.
